#
# metrics-mon-port is definedf in service 'mq-prometheus'
#
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-mq-monitor
  name: mq-prometheus-metrics-mon
spec:
  endpoints:
  - interval: 30s
    port: metrics-mon
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: mq02-ibm-mq-metrics-mon
 
 