apiVersion: v1
data:
  mq02-prometheus.mqsc: |
    * Cleanup any existing service
    STOP SERVICE(MQPROMETHEUS)
    DELETE SERVICE(MQPROMETHEUS)

    * Reset the definition
    * This is a customized version using a non-default listener-port.
    DEFINE SERVICE(MQPROMETHEUS)         +
          CONTROL(QMGR)               +
          SERVTYPE(SERVER)            +
          STARTCMD('/opt/mqm/metrics/mq_prometheus.sh') +
          STARTARG('+QMNAME+ 9156')          +
          STOPCMD('/usr/bin/kill ' )  +
          STOPARG(+MQ_SERVER_PID+)    +
          STDOUT('/var/mqm/errors/mq_prometheus.out')  +
          STDERR('/var/mqm/errors/mq_prometheus.out')  +
          DESCR('MQ exporter for Prometheus')

    * Start it manually now; will be automatically started on future qmgr startup
    START SERVICE(MQPROMETHEUS)
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mq02-prometheus-mqsc
  namespace: mq-demo
