apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq02
spec:
  license:
    accept: true
    license: L-AXAF-JLZ53A
    use: Development
  queueManager:
    debug: false
    image: image-registry.openshift-image-registry.svc:5000/mq-demo/mq-with-metrics:9.3.3.1-r1
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 1
      initialDelaySeconds: 90
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    logFormat: Basic
    metrics:
      enabled: true
    name: MQ02
    mqsc:
      - configMap:
          name: mq02-mqsc
          items:
            - mq02.mqsc
      - configMap:
          name: mq02-prometheus-mqsc
          items:
            - mq02-prometheus.mqsc
    readinessProbe:
      failureThreshold: 1
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: "300m"
        memory: 1Gi
      requests:
        cpu: "200m"
        memory: 1Gi
    availability:
      type: SingleInstance
    storage:
      defaultClass: ibmc-vpc-block-metro-retain-10iops-tier
      queueManager:
        type: persistent-claim
      persistedData:
        enabled: true
      recoveryLogs:
        enabled: true
  securityContext:
    initVolumeAsRoot: false
  template:
    pod:
      containers:
        - name: qmgr
          envFrom:
            - configMapRef:
                name: metrics-configuration
          env:
            - name: MQSNOAUT
              value: "yes"
            - name: MQ_DEV
              value: "true"
            - name: MQ_CONNAUTH_USE_HTP
              value: "true"
            - name: MQ_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mq02-admin-password
                  key: admin-password
          ports:
            - containerPort: 9157
              protocol: TCP
  terminationGracePeriodSeconds: 30
  tracing:
    agent: {}
    collector: {}
    enabled: false
    namespace: ""
  version: 9.3.3.1-r1
  web:
    enabled: true
