# Use a different name for the port, than the standard for MQ to avoid conflict
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '9157'
    prometheus.io/scrape: 'true'
  name: mq-prometheus
  labels:
    app.kubernetes.io/name: mq02-ibm-mq-metrics-mon
spec:
  selector:
    app.kubernetes.io/instance: mq02-qm
  ports:
    - name: metrics-mon
      protocol: TCP
      port: 9157
      targetPort: 9156

